### Задание 1

Дан массив Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]

требуется преобразовать его в массив вида R = [[1,2,3,4],[2,3,4,5],[3,4,5,6],.....,[11,12,13,14]]

In [1]:
import numpy as np
from numpy.lib import stride_tricks
from scipy import optimize
from scipy.optimize import golden, rosen_der

In [2]:
#задаем массив
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]

In [3]:
#для решения задачи нам потребуются переменные которые мы будем передавать как аргументы в функцию transform_array
a = Z[0]
b = len(Z)

In [4]:
def transform_array(a, size_of_column):
    """
    Функция transform_array принимает на вход одномерный массив
    Z и возвращает многомерный массив 
    """
    shape = (a.size - size_of_column + 1, size_of_column) 
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape= shape, strides= strides, writeable= False)

In [5]:
%%time
R = transform_array(np.arange(a, b + 1), 4)

CPU times: user 95 µs, sys: 28 µs, total: 123 µs
Wall time: 120 µs


In [6]:
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

### Задание 2

Дана произвольная матрица A. Рассчитать ранг матрицы A.

In [7]:
C = np.random.uniform(0, 10, (2, 2))
C

array([[1.78599544, 9.932727  ],
       [2.29956082, 9.45734437]])

In [8]:
def matrix_rank_definer(A):
    """
    Функция matrix_rank_definer возвращает ранг матрицы
    """
    return np.linalg.matrix_rank(A)

In [9]:
matrix_rank_definer(C)

2

### Задание 3 


Найти лучший алгоритм для решения следующей задачи:
min (x1x4(x1+x2+x3)+x3).

Условия:

x1x2x3x4≥30

x1^2+x2^2+x3^2+x4^2=60

2≤x1,x2,x3,x4≤6

Начальное приближение:
x=(1,5,5,1)

In [10]:
#задаю функцию которая возвращает нашу задачу (x1x4(x1+x2+x3)+x3)

fun = lambda x: (x[0] * x[3] * (x[0] + x[1] + x[2]) + x[2])

In [11]:
#задаем условия задачи

#cons возвращает первое условие x1x2x3x4≥30 и второе условие x1^2+x2^2+x3^2+x4^2=60
cons = ({'type': 'ineq', 'fun': lambda x: x[0] * x[1] * x[2] * x[3] >= 30},
       {'type': 'eq', 'fun': lambda x: x[0]**2 + x[1]**2 + x[2]**2 + x[3]**2 == 60})

#bnds возврращает следующие условие 2≤x1,x2,x3,x4≤6
bnds = ((2,6),(2,6),(2,6),(2,6))

In [12]:
#используем алгоритм оптимизации 'TNC' он принимает наши диапазоны bnds но не хочет принимать cons
#оптимизируем без учета cons
res_0 = optimize.minimize(fun, (1,5,5,1) , method= 'TNC',   bounds= bnds)

In [13]:
#алгоритм отработал мы получили минимумы
res_TNC = res_0.x
res_TNC

array([2., 2., 2., 2.])

In [14]:
#используем алгоритм оптимизации 'L-BFGS-B' он принимает наши диапазоны bnds но не хочет принимать cons
#оптимизируем без учета cons
res_1 = optimize.minimize(fun, (1,5,5,1) , method= 'L-BFGS-B',   bounds= bnds)

In [15]:
#алгоритм отработал мы получили минимумы при этом что интересно мы получили 100% содимость с результатом 'TNC'
res_L_BFGS_B = res_1.x
res_L_BFGS_B

array([2., 2., 2., 2.])

In [16]:
#используем алгоритм оптимизации 'COBYLA' он не принимает ни один из начальных условий задачи
res_COBYLA = optimize.minimize(fun, (1,5,5,1) , method= 'COBYLA')

In [17]:
x_min_cobyla = res_COBYLA.x
x_min_cobyla

array([ 305.09588998,   76.46005944,  151.84919019, -256.66915106])

In [18]:
#используем алгоритм оптимизации 'Nelder-Mead' он не принимает ни один из начальных условий задачи
res_Nelder_Mead = optimize.minimize(fun, (1,5,5,1) , method= 'Nelder-Mead')

In [19]:
x_min_Nelder_Mead = res_Nelder_Mead.x
x_min_Nelder_Mead

array([ 1.45959526e+48,  9.74919738e+49, -3.83111448e+49, -3.75034058e+49])

In [20]:
#используем алгоритм оптимизации 'CG' он не принимает ни один из начальных условий задачи
res_CG = optimize.minimize(fun, (1,5,5,1) , method= 'CG')

In [248]:
x_min_CG = res_CG.x
x_min_Nelder_Mead

array([ 1.45959526e+48,  9.74919738e+49, -3.83111448e+49, -3.75034058e+49])